GET https://limitless-brushlands-30045.herokuapp.com

###
POST https://limitless-brushlands-30045.herokuapp.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Liisa Marttinen",
    "number": "040-243563"
}

###
DELETE  https://limitless-brushlands-30045.herokuapp.com/api/persons/3 HTTP/1.1



###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

    {
      "name": "zzabvvz",
      "number": "091-1234576"
    }


###
# new id may need to be inserted before deletion
DELETE  http://localhost:3001/api/persons/629e96d8f418b326aad64bee1 HTTP/1.1

###
PUT  http://localhost:3001/api/persons/629e96d8f418b326aad64bee1 HTTP/1.1
content-type: application/json

    {
      "name" : "d",
      "number": "12234323"
    }